site_name: AI Research Oracle
site_description: Predicting AI paper impact using early signals
site_author: AI Research Oracle Team
site_url: https://hretheum.github.io/ai_oracle

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        pl:
          name: Polski
          build: true
          site_name: AI Research Oracle
      nav_translations:
        pl:
          Home: Strona główna
          Strategy: Strategia
          Business Plan: Plan biznesowy
          Pivot Story: Historia pivotu
          Technical: Dokumentacja techniczna
          Implementation: Implementacja
          API Reference: Dokumentacja API
          Algorithms: Algorytmy
          ML Training: Trening ML
          Operations: Operacje
          Roadmap: Mapa drogowa
          Metrics: Metryki
          Budget: Budżet
          Newsletter: Newsletter
          Resources: Zasoby
          Case Studies: Studia przypadków
          Platforms: Platformy
          Pitch Deck: Pitch Deck

nav:
  - Home: index.md
  - Strategy:
    - Business Plan: strategy/business-plan.md
    - Pivot Story: strategy/pivot-story.md
  - Technical:
    - Implementation: technical/implementation-guide.md
    - API Reference: technical/api-reference.md
    - Algorithms: technical/algorithms.md
    - ML Training: technical/ml-training-guide.md
  - Operations:
    - Roadmap: operations/roadmap.md
    - Metrics: operations/metrics.md
    - Budget: operations/budget.md
    - Newsletter: operations/newsletter-strategy.md
  - Resources:
    - Case Studies: resources/case-study-example.md
    - Platforms: resources/platform_comparison.md
    - Pitch Deck: GAMMA_PITCH_DECK_PROMPT.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hretheum/ai_oracle
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AIResearchOracle

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg